"""initial_schema

Revision ID: a5102354f2c3
Revises: 
Create Date: 2026-06-12 02:08:18.143559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5102354f2c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('consent_date', sa.Date(), nullable=True),
    sa.Column('consent_version', sa.String(), nullable=True),
    sa.Column('consent_status', sa.Enum('CONSENTED', 'PENDING', 'WITHDRAWN', 'ASSENT_ONLY', name='consentstatus'), nullable=True),
    sa.Column('guardian_consent', sa.String(), nullable=True),
    sa.Column('assent_status', sa.String(), nullable=True),
    sa.Column('consent_withdrawn', sa.String(), nullable=True),
    sa.Column('withdrawal_reason', sa.String(), nullable=True),
    sa.Column('re_consent_required', sa.String(), nullable=True),
    sa.Column('re_consent_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='neps_core'
    )
    op.create_table('distress_screenings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('screening_date', sa.Date(), nullable=True),
    sa.Column('distress_score', sa.Float(), nullable=True),
    sa.Column('suicidality_flag', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='risklevel'), nullable=True),
    sa.Column('trigger_form', sa.String(), nullable=True),
    sa.Column('trigger_item', sa.String(), nullable=True),
    sa.Column('assigned_responder', sa.String(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('referral_made', sa.String(), nullable=True),
    sa.Column('referral_destination', sa.String(), nullable=True),
    sa.Column('welfare_check_due', sa.Date(), nullable=True),
    sa.Column('resolution_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='neps_core'
    )
    op.create_index(op.f('ix_neps_core_distress_screenings_record_id'), 'distress_screenings', ['record_id'], unique=False, schema='neps_core')
    op.create_table('participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('redcap_event_name', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('site', sa.String(), nullable=False),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('grade_level', sa.String(), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.Column('cohort_status', sa.Enum('ACTIVE', 'INACTIVE', 'WITHDRAWN', name='cohortstatus'), nullable=True),
    sa.Column('phone_contact', sa.String(), nullable=True),
    sa.Column('consent_status', sa.Enum('CONSENTED', 'PENDING', 'WITHDRAWN', 'ASSENT_ONLY', name='consentstatus'), nullable=True),
    sa.Column('redcap_data_access_group', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='neps_core'
    )
    op.create_index(op.f('ix_neps_core_participants_country'), 'participants', ['country'], unique=False, schema='neps_core')
    op.create_index(op.f('ix_neps_core_participants_record_id'), 'participants', ['record_id'], unique=True, schema='neps_core')
    op.create_index(op.f('ix_neps_core_participants_site'), 'participants', ['site'], unique=False, schema='neps_core')
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referral_id', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('initiation_date', sa.Date(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('INITIATED', 'IN_PROGRESS', 'COMPLETED', name='referralstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_id'),
    schema='neps_core'
    )
    op.create_index(op.f('ix_neps_core_referrals_record_id'), 'referrals', ['record_id'], unique=False, schema='neps_core')
    op.create_table('survey_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('redcap_event_name', sa.String(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('survey_date', sa.Date(), nullable=True),
    sa.Column('survey_complete', sa.Enum('COMPLETE', 'UNVERIFIED', 'INCOMPLETE', name='surveystatus'), nullable=True),
    sa.Column('perceived_stress_score', sa.Float(), nullable=True),
    sa.Column('mood_status', sa.String(), nullable=True),
    sa.Column('anxiety_score', sa.Float(), nullable=True),
    sa.Column('depression_score', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.String(), nullable=True),
    sa.Column('daily_functioning', sa.Float(), nullable=True),
    sa.Column('fatigue_level', sa.String(), nullable=True),
    sa.Column('school_attendance_days', sa.Integer(), nullable=True),
    sa.Column('social_isolation_score', sa.Float(), nullable=True),
    sa.Column('coping_behaviours', sa.String(), nullable=True),
    sa.Column('substance_use', sa.String(), nullable=True),
    sa.Column('suicidality_screening', sa.String(), nullable=True),
    sa.Column('self_esteem_score', sa.Float(), nullable=True),
    sa.Column('loneliness_score', sa.Float(), nullable=True),
    sa.Column('risk_flag', sa.String(), nullable=True),
    sa.Column('requires_follow_up', sa.String(), nullable=True),
    sa.Column('redcap_repeat_instrument', sa.String(), nullable=True),
    sa.Column('redcap_repeat_instance', sa.String(), nullable=True),
    sa.Column('examination_stress', sa.Float(), nullable=True),
    sa.Column('academic_pressure', sa.Float(), nullable=True),
    sa.Column('homework_burden', sa.Float(), nullable=True),
    sa.Column('school_climate', sa.String(), nullable=True),
    sa.Column('bullying_exposure', sa.String(), nullable=True),
    sa.Column('harsh_discipline', sa.String(), nullable=True),
    sa.Column('educational_aspirations', sa.String(), nullable=True),
    sa.Column('fear_of_failure', sa.Float(), nullable=True),
    sa.Column('teacher_support', sa.Float(), nullable=True),
    sa.Column('counselling_access', sa.String(), nullable=True),
    sa.Column('household_assets', sa.Integer(), nullable=True),
    sa.Column('food_insecurity', sa.String(), nullable=True),
    sa.Column('economic_strain', sa.Float(), nullable=True),
    sa.Column('employment_pressure', sa.String(), nullable=True),
    sa.Column('financial_stress', sa.Float(), nullable=True),
    sa.Column('digital_access', sa.String(), nullable=True),
    sa.Column('household_instability', sa.String(), nullable=True),
    sa.Column('internalised_stigma', sa.Float(), nullable=True),
    sa.Column('community_stigma', sa.Float(), nullable=True),
    sa.Column('family_stigma', sa.Float(), nullable=True),
    sa.Column('school_stigma', sa.Float(), nullable=True),
    sa.Column('mental_health_literacy', sa.Float(), nullable=True),
    sa.Column('help_seeking_intention', sa.String(), nullable=True),
    sa.Column('help_seeking_behaviour', sa.String(), nullable=True),
    sa.Column('awareness_of_services', sa.String(), nullable=True),
    sa.Column('resilience_score', sa.Float(), nullable=True),
    sa.Column('social_support', sa.Float(), nullable=True),
    sa.Column('family_connectedness', sa.Float(), nullable=True),
    sa.Column('peer_support', sa.Float(), nullable=True),
    sa.Column('community_connectedness', sa.Float(), nullable=True),
    sa.Column('religious_support', sa.Float(), nullable=True),
    sa.Column('school_belonging', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='neps_core'
    )
    op.create_index(op.f('ix_neps_core_survey_responses_record_id'), 'survey_responses', ['record_id'], unique=False, schema='neps_core')
    op.create_table('wp6_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('attendance', sa.String(), nullable=True),
    sa.Column('engagement_level', sa.Float(), nullable=True),
    sa.Column('fidelity_score', sa.Float(), nullable=True),
    sa.Column('satisfaction_score', sa.Float(), nullable=True),
    sa.Column('homework_completion', sa.String(), nullable=True),
    sa.Column('distress_pre', sa.Float(), nullable=True),
    sa.Column('distress_post', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='neps_core'
    )
    op.create_index(op.f('ix_neps_core_wp6_sessions_record_id'), 'wp6_sessions', ['record_id'], unique=False, schema='neps_core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_neps_core_wp6_sessions_record_id'), table_name='wp6_sessions', schema='neps_core')
    op.drop_table('wp6_sessions', schema='neps_core')
    op.drop_index(op.f('ix_neps_core_survey_responses_record_id'), table_name='survey_responses', schema='neps_core')
    op.drop_table('survey_responses', schema='neps_core')
    op.drop_index(op.f('ix_neps_core_referrals_record_id'), table_name='referrals', schema='neps_core')
    op.drop_table('referrals', schema='neps_core')
    op.drop_index(op.f('ix_neps_core_participants_site'), table_name='participants', schema='neps_core')
    op.drop_index(op.f('ix_neps_core_participants_record_id'), table_name='participants', schema='neps_core')
    op.drop_index(op.f('ix_neps_core_participants_country'), table_name='participants', schema='neps_core')
    op.drop_table('participants', schema='neps_core')
    op.drop_index(op.f('ix_neps_core_distress_screenings_record_id'), table_name='distress_screenings', schema='neps_core')
    op.drop_table('distress_screenings', schema='neps_core')
    op.drop_table('consent_records', schema='neps_core')
    # ### end Alembic commands ###
