"""Add foreign key constraints to record_id

Revision ID: b2396d7fdcf4
Revises: a5102354f2c3
Create Date: 2023-10-25 00:11:13.803821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2396d7fdcf4'
down_revision = 'a5102354f2c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_consent_records_record_id', 'consent_records', 'participants', ['record_id'], ['record_id'], source_schema='neps_core', referent_schema='neps_core', ondelete='CASCADE')
    op.create_foreign_key('fk_survey_responses_record_id', 'survey_responses', 'participants', ['record_id'], ['record_id'], source_schema='neps_core', referent_schema='neps_core', ondelete='CASCADE')
    op.create_foreign_key('fk_distress_screenings_record_id', 'distress_screenings', 'participants', ['record_id'], ['record_id'], source_schema='neps_core', referent_schema='neps_core', ondelete='CASCADE')
    op.create_foreign_key('fk_referrals_record_id', 'referrals', 'participants', ['record_id'], ['record_id'], source_schema='neps_core', referent_schema='neps_core', ondelete='CASCADE')
    op.create_foreign_key('fk_wp6_sessions_record_id', 'wp6_sessions', 'participants', ['record_id'], ['record_id'], source_schema='neps_core', referent_schema='neps_core', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_wp6_sessions_record_id', 'wp6_sessions', schema='neps_core', type_='foreignkey')
    op.drop_constraint('fk_referrals_record_id', 'referrals', schema='neps_core', type_='foreignkey')
    op.drop_constraint('fk_distress_screenings_record_id', 'distress_screenings', schema='neps_core', type_='foreignkey')
    op.drop_constraint('fk_survey_responses_record_id', 'survey_responses', schema='neps_core', type_='foreignkey')
    op.drop_constraint('fk_consent_records_record_id', 'consent_records', schema='neps_core', type_='foreignkey')
    # ### end Alembic commands ###
